"""

Revision ID: 57f6c99e3790
Revises: 39034170d5cf
Create Date: 2026-04-17 08:23:10.367481

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '57f6c99e3790'
down_revision: Union[str, None] = '39034170d5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('odometer_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'odometer_updated_at')
    # ### end Alembic commands ###
